[workspace]
resolver = "2"

members = [
    "contracts/crowdfund",
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[patch.crates-io]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "06e73968" }
soroban-auth = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "06e73968" }
soroban-sdk-macros = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "06e73968" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
soroban-env-guest = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "c8bc71d" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "fee9a43" }
